
// Objective-C API for talking to the following Go packages
//
//	github.com/Next-Social-Platform/im-chat-sdk-core/im_chat_sdk
//	github.com/Next-Social-Platform/im-chat-sdk-core/im_chat_sdk_callback
//
// File is generated by gomobile bind. Do not edit.
#ifndef __ImChatCore_FRAMEWORK_H__
#define __ImChatCore_FRAMEWORK_H__

#include "Im_chat_sdk.objc.h"
#include "Im_chat_sdk_callback.objc.h"
#include "Universe.objc.h"

#endif
