// Objective-C API for talking to github.com/Next-Social-Platform/im-chat-sdk-core/im_chat_sdk Go package.
//   gobind -lang=objc github.com/Next-Social-Platform/im-chat-sdk-core/im_chat_sdk
//
// File is generated by gobind. Do not edit.

#ifndef __Im_chat_sdk_H__
#define __Im_chat_sdk_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"

#include "Im_chat_sdk_callback.objc.h"

@class Im_chat_sdkLoginMgr;

@interface Im_chat_sdkLoginMgr : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init;
- (id<Im_chat_sdk_callbackOnAdvancedMsgListener> _Nullable)advancedMsgListener;
// skipped method LoginMgr.BaseCtx with unsupported parameter or return types

- (id<Im_chat_sdk_callbackOnBatchMsgListener> _Nullable)batchMsgListener;
- (id<Im_chat_sdk_callbackOnCustomBusinessListener> _Nullable)businessListener;
// skipped method LoginMgr.Contact with unsupported parameter or return types

- (id<Im_chat_sdk_callbackContactListener> _Nullable)contactListener;
// skipped method LoginMgr.Context with unsupported parameter or return types

// skipped method LoginMgr.Conversation with unsupported parameter or return types

- (id<Im_chat_sdk_callbackOnConversationListener> _Nullable)conversationListener;
- (void)exit;
// skipped method LoginMgr.File with unsupported parameter or return types

// skipped method LoginMgr.Friend with unsupported parameter or return types

- (id<Im_chat_sdk_callbackOnFriendshipListener> _Nullable)friendListener;
// skipped method LoginMgr.Full with unsupported parameter or return types

// skipped method LoginMgr.GetLoginStatus with unsupported parameter or return types

- (NSString* _Nonnull)getLoginUserID;
- (NSString* _Nonnull)getToken;
// skipped method LoginMgr.Group with unsupported parameter or return types

- (id<Im_chat_sdk_callbackOnGroupListener> _Nullable)groupListener;
// skipped method LoginMgr.ImConfig with unsupported parameter or return types

// skipped method LoginMgr.ImUser with unsupported parameter or return types

// skipped method LoginMgr.InitSDK with unsupported parameter or return types

// skipped method LoginMgr.Login with unsupported parameter or return types

// skipped method LoginMgr.Logout with unsupported parameter or return types

- (id<Im_chat_sdk_callbackOnMessageKvInfoListener> _Nullable)msgKvListener;
// skipped method LoginMgr.NetworkStatusChanged with unsupported parameter or return types

- (void)setAdvancedMsgListener:(id<Im_chat_sdk_callbackOnAdvancedMsgListener> _Nullable)advancedMsgListener;
// skipped method LoginMgr.SetAppBackgroundStatus with unsupported parameter or return types

- (void)setBatchMsgListener:(id<Im_chat_sdk_callbackOnBatchMsgListener> _Nullable)batchMsgListener;
- (void)setContactListener:(id<Im_chat_sdk_callbackContactListener> _Nullable)contactListener;
- (void)setConversationListener:(id<Im_chat_sdk_callbackOnConversationListener> _Nullable)conversationListener;
- (void)setCustomBusinessListener:(id<Im_chat_sdk_callbackOnCustomBusinessListener> _Nullable)listener;
- (void)setFriendListener:(id<Im_chat_sdk_callbackOnFriendshipListener> _Nullable)friendListener;
- (void)setGroupListener:(id<Im_chat_sdk_callbackOnGroupListener> _Nullable)groupListener;
- (void)setMessageKvInfoListener:(id<Im_chat_sdk_callbackOnMessageKvInfoListener> _Nullable)messageKvInfoListener;
- (void)setUserListener:(id<Im_chat_sdk_callbackOnUserListener> _Nullable)userListener;
- (id<Im_chat_sdk_callbackOnSignalingListener> _Nullable)signalingListener;
// skipped method LoginMgr.Third with unsupported parameter or return types

- (void)unInitSDK;
// skipped method LoginMgr.User with unsupported parameter or return types

- (id<Im_chat_sdk_callbackOnUserListener> _Nullable)userListener;
@end

FOUNDATION_EXPORT const int64_t Im_chat_sdkLogged;
FOUNDATION_EXPORT const int64_t Im_chat_sdkLogging;
FOUNDATION_EXPORT const int64_t Im_chat_sdkLogoutStatus;
FOUNDATION_EXPORT NSString* _Nonnull const Im_chat_sdkLogoutTips;

@interface Im_chat_sdk : NSObject
+ (NSError* _Nullable) errNotImplemented;
+ (void) setErrNotImplemented:(NSError* _Nullable)v;

/**
 * UserForSDK Client-independent user class
 */
+ (Im_chat_sdkLoginMgr* _Nullable) userForSDK;
+ (void) setUserForSDK:(Im_chat_sdkLoginMgr* _Nullable)v;

@end

FOUNDATION_EXPORT void Im_chat_sdkAcceptFriendApplication(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable userIDHandleMsg);

FOUNDATION_EXPORT void Im_chat_sdkAcceptGroupApplication(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable groupID, NSString* _Nullable fromUserID, NSString* _Nullable handleMsg);

FOUNDATION_EXPORT void Im_chat_sdkAddBlack(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable blackUserID, NSString* _Nullable ex);

FOUNDATION_EXPORT void Im_chat_sdkAddFriend(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable userIDReqMsg);

// skipped function AddMessageReactionExtensions with unsupported parameter or return types


/**
 * AddUserCommand add to user's favorite
 */
FOUNDATION_EXPORT void Im_chat_sdkAddUserCommand(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, int32_t Type, NSString* _Nullable uuid, NSString* _Nullable value);

FOUNDATION_EXPORT void Im_chat_sdkChangeGroupMemberMute(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable groupID, NSString* _Nullable userID, long mutedSeconds);

FOUNDATION_EXPORT void Im_chat_sdkChangeGroupMute(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable groupID, BOOL isMute);

FOUNDATION_EXPORT void Im_chat_sdkChangeInputStates(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable conversationID, BOOL focus);

FOUNDATION_EXPORT void Im_chat_sdkCheckFriend(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable userIDList);

/**
 * CheckResourceLoad checks the SDK is resource load status.
 */
FOUNDATION_EXPORT BOOL Im_chat_sdkCheckResourceLoad(Im_chat_sdkLoginMgr* _Nullable uSDK, NSString* _Nullable funcName, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT void Im_chat_sdkClearConversationAndDeleteAllMsg(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable conversationID);

FOUNDATION_EXPORT NSString* _Nonnull Im_chat_sdkCreateAdvancedQuoteMessage(NSString* _Nullable operationID, NSString* _Nullable text, NSString* _Nullable message, NSString* _Nullable messageEntityList);

FOUNDATION_EXPORT NSString* _Nonnull Im_chat_sdkCreateAdvancedTextMessage(NSString* _Nullable operationID, NSString* _Nullable text, NSString* _Nullable messageEntityList);

FOUNDATION_EXPORT NSString* _Nonnull Im_chat_sdkCreateCardMessage(NSString* _Nullable operationID, NSString* _Nullable cardInfo);

FOUNDATION_EXPORT NSString* _Nonnull Im_chat_sdkCreateCustomMessage(NSString* _Nullable operationID, NSString* _Nullable data, NSString* _Nullable extension, NSString* _Nullable description);

FOUNDATION_EXPORT NSString* _Nonnull Im_chat_sdkCreateFaceMessage(NSString* _Nullable operationID, long index, NSString* _Nullable data);

FOUNDATION_EXPORT NSString* _Nonnull Im_chat_sdkCreateFileMessage(NSString* _Nullable operationID, NSString* _Nullable filePath, NSString* _Nullable fileName);

FOUNDATION_EXPORT NSString* _Nonnull Im_chat_sdkCreateFileMessageByURL(NSString* _Nullable operationID, NSString* _Nullable fileBaseInfo);

FOUNDATION_EXPORT NSString* _Nonnull Im_chat_sdkCreateFileMessageFromFullPath(NSString* _Nullable operationID, NSString* _Nullable fileFullPath, NSString* _Nullable fileName);

FOUNDATION_EXPORT NSString* _Nonnull Im_chat_sdkCreateForwardMessage(NSString* _Nullable operationID, NSString* _Nullable m);

FOUNDATION_EXPORT void Im_chat_sdkCreateGroup(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable groupReqInfo);

FOUNDATION_EXPORT NSString* _Nonnull Im_chat_sdkCreateImageMessage(NSString* _Nullable operationID, NSString* _Nullable imagePath);

FOUNDATION_EXPORT NSString* _Nonnull Im_chat_sdkCreateImageMessageByURL(NSString* _Nullable operationID, NSString* _Nullable sourcePath, NSString* _Nullable sourcePicture, NSString* _Nullable bigPicture, NSString* _Nullable snapshotPicture);

FOUNDATION_EXPORT NSString* _Nonnull Im_chat_sdkCreateImageMessageFromFullPath(NSString* _Nullable operationID, NSString* _Nullable imageFullPath);

FOUNDATION_EXPORT NSString* _Nonnull Im_chat_sdkCreateLocationMessage(NSString* _Nullable operationID, NSString* _Nullable description, double longitude, double latitude);

FOUNDATION_EXPORT NSString* _Nonnull Im_chat_sdkCreateMergerMessage(NSString* _Nullable operationID, NSString* _Nullable messageList, NSString* _Nullable title, NSString* _Nullable summaryList);

FOUNDATION_EXPORT NSString* _Nonnull Im_chat_sdkCreateQuoteMessage(NSString* _Nullable operationID, NSString* _Nullable text, NSString* _Nullable message);

FOUNDATION_EXPORT NSString* _Nonnull Im_chat_sdkCreateReactionMessage(NSString* _Nullable operationID, NSString* _Nullable clientMsgID, NSString* _Nullable reaction, int32_t status);

FOUNDATION_EXPORT NSString* _Nonnull Im_chat_sdkCreateSoundMessage(NSString* _Nullable operationID, NSString* _Nullable soundPath, int64_t duration);

FOUNDATION_EXPORT NSString* _Nonnull Im_chat_sdkCreateSoundMessageByURL(NSString* _Nullable operationID, NSString* _Nullable soundBaseInfo);

FOUNDATION_EXPORT NSString* _Nonnull Im_chat_sdkCreateSoundMessageFromFullPath(NSString* _Nullable operationID, NSString* _Nullable soundPath, int64_t duration);

FOUNDATION_EXPORT NSString* _Nonnull Im_chat_sdkCreateTextAtMessage(NSString* _Nullable operationID, NSString* _Nullable text, NSString* _Nullable atUserList, NSString* _Nullable atUsersInfo, NSString* _Nullable message);

FOUNDATION_EXPORT NSString* _Nonnull Im_chat_sdkCreateTextMessage(NSString* _Nullable operationID, NSString* _Nullable text);

FOUNDATION_EXPORT NSString* _Nonnull Im_chat_sdkCreateVideoMessage(NSString* _Nullable operationID, NSString* _Nullable videoPath, NSString* _Nullable videoType, int64_t duration, NSString* _Nullable snapshotPath);

FOUNDATION_EXPORT NSString* _Nonnull Im_chat_sdkCreateVideoMessageByURL(NSString* _Nullable operationID, NSString* _Nullable videoBaseInfo);

FOUNDATION_EXPORT NSString* _Nonnull Im_chat_sdkCreateVideoMessageFromFullPath(NSString* _Nullable operationID, NSString* _Nullable videoFullPath, NSString* _Nullable videoType, int64_t duration, NSString* _Nullable snapshotFullPath);

FOUNDATION_EXPORT void Im_chat_sdkDeleteAllMsgFromLocal(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID);

FOUNDATION_EXPORT void Im_chat_sdkDeleteAllMsgFromLocalAndSvr(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID);

FOUNDATION_EXPORT void Im_chat_sdkDeleteConversationAndDeleteAllMsg(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable conversationID);

FOUNDATION_EXPORT void Im_chat_sdkDeleteFriend(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable friendUserID);

FOUNDATION_EXPORT void Im_chat_sdkDeleteMessage(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable conversationID, NSString* _Nullable clientMsgID);

FOUNDATION_EXPORT void Im_chat_sdkDeleteMessageFromLocalStorage(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable conversationID, NSString* _Nullable clientMsgID);

/**
 * DeleteUserCommand delete from user's favorite
 */
FOUNDATION_EXPORT void Im_chat_sdkDeleteUserCommand(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, int32_t Type, NSString* _Nullable uuid);

FOUNDATION_EXPORT void Im_chat_sdkDismissGroup(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable groupID);

FOUNDATION_EXPORT void Im_chat_sdkFindMessageList(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable findMessageOptions);

FOUNDATION_EXPORT void Im_chat_sdkGetAdvancedHistoryMessageList(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable getMessageOptions);

FOUNDATION_EXPORT void Im_chat_sdkGetAdvancedHistoryMessageListReverse(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable getMessageOptions);

FOUNDATION_EXPORT void Im_chat_sdkGetAllConversationList(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID);

/**
 * GetAllUserCommands get user's favorite
 */
FOUNDATION_EXPORT void Im_chat_sdkGetAllUserCommands(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, int32_t Type);

FOUNDATION_EXPORT void Im_chat_sdkGetAppConfig(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID);

FOUNDATION_EXPORT NSString* _Nonnull Im_chat_sdkGetAtAllTag(NSString* _Nullable operationID);

FOUNDATION_EXPORT void Im_chat_sdkGetBlackList(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID);

FOUNDATION_EXPORT void Im_chat_sdkGetContactList(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID);

FOUNDATION_EXPORT NSString* _Nonnull Im_chat_sdkGetConversationIDBySessionType(NSString* _Nullable operationID, NSString* _Nullable sourceID, long sessionType);

FOUNDATION_EXPORT void Im_chat_sdkGetConversationListSplit(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, long offset, long count, long ctype);

/**
 * deprecated
 */
FOUNDATION_EXPORT void Im_chat_sdkGetConversationRecvMessageOpt(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable conversationIDList);

FOUNDATION_EXPORT void Im_chat_sdkGetFriendApplicationListAsApplicant(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID);

FOUNDATION_EXPORT void Im_chat_sdkGetFriendApplicationListAsRecipient(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID);

FOUNDATION_EXPORT void Im_chat_sdkGetFriendList(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID);

FOUNDATION_EXPORT void Im_chat_sdkGetFriendListPage(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, int32_t offset, int32_t count);

FOUNDATION_EXPORT void Im_chat_sdkGetFullUserInfo(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable userIDs);

FOUNDATION_EXPORT void Im_chat_sdkGetGroupApplicationListAsApplicant(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID);

FOUNDATION_EXPORT void Im_chat_sdkGetGroupApplicationListAsRecipient(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID);

FOUNDATION_EXPORT void Im_chat_sdkGetGroupConversationListSplit(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, long offset, long count);

FOUNDATION_EXPORT void Im_chat_sdkGetGroupMemberList(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable groupID, int32_t filter, int32_t offset, int32_t count);

FOUNDATION_EXPORT void Im_chat_sdkGetGroupMemberListByJoinTimeFilter(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable groupID, int32_t offset, int32_t count, int64_t joinTimeBegin, int64_t joinTimeEnd, NSString* _Nullable filterUserIDList);

FOUNDATION_EXPORT void Im_chat_sdkGetGroupMemberOwnerAndAdmin(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable groupID);

FOUNDATION_EXPORT void Im_chat_sdkGetInputStates(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable conversationID, NSString* _Nullable userID);

FOUNDATION_EXPORT void Im_chat_sdkGetJoinedGroupList(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID);

FOUNDATION_EXPORT long Im_chat_sdkGetLoginStatus(NSString* _Nullable operationID);

FOUNDATION_EXPORT NSString* _Nonnull Im_chat_sdkGetLoginUserID(void);

FOUNDATION_EXPORT void Im_chat_sdkGetMultipleConversation(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable conversationIDList);

FOUNDATION_EXPORT void Im_chat_sdkGetOneConversation(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, int32_t sessionType, NSString* _Nullable sourceID);

FOUNDATION_EXPORT NSString* _Nonnull Im_chat_sdkGetSdkVersion(void);

/**
 * GetSelfUserInfo obtains the user's own information.
 */
FOUNDATION_EXPORT void Im_chat_sdkGetSelfUserInfo(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID);

FOUNDATION_EXPORT void Im_chat_sdkGetSpecifiedFriendsInfo(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable userIDList);

FOUNDATION_EXPORT void Im_chat_sdkGetSpecifiedGroupMembersInfo(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable groupID, NSString* _Nullable userIDList);

FOUNDATION_EXPORT void Im_chat_sdkGetSpecifiedGroupsInfo(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable groupIDList);

/**
 * GetSubscribeUsersStatus Get the online status of subscribers.
 */
FOUNDATION_EXPORT void Im_chat_sdkGetSubscribeUsersStatus(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID);

FOUNDATION_EXPORT void Im_chat_sdkGetTotalUnreadMsgCount(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID);

/**
 * GetUserStatus Get the online status of users.
 */
FOUNDATION_EXPORT void Im_chat_sdkGetUserStatus(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable userIDs);

FOUNDATION_EXPORT void Im_chat_sdkGetUsersInfo(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable userIDs);

/**
 * GetUsersInfoFromSrv obtains the information about multiple users.
 */
FOUNDATION_EXPORT void Im_chat_sdkGetUsersInfoFromSrv(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable userIDs);

FOUNDATION_EXPORT void Im_chat_sdkGetUsersInfoWithCache(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable userIDs, NSString* _Nullable groupID);

FOUNDATION_EXPORT void Im_chat_sdkHideAllConversations(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID);

FOUNDATION_EXPORT void Im_chat_sdkHideConversation(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable conversationID);

FOUNDATION_EXPORT BOOL Im_chat_sdkInitSDK(id<Im_chat_sdk_callbackOnConnListener> _Nullable listener, NSString* _Nullable operationID, NSString* _Nullable config);

FOUNDATION_EXPORT void Im_chat_sdkInsertGroupMessageToLocalStorage(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable message, NSString* _Nullable groupID, NSString* _Nullable sendID);

FOUNDATION_EXPORT void Im_chat_sdkInsertSingleMessageToLocalStorage(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable message, NSString* _Nullable recvID, NSString* _Nullable sendID);

FOUNDATION_EXPORT void Im_chat_sdkInviteUserToGroup(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable groupID, NSString* _Nullable reason, NSString* _Nullable userIDList);

FOUNDATION_EXPORT void Im_chat_sdkIsJoinGroup(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable groupID);

FOUNDATION_EXPORT void Im_chat_sdkJoinGroup(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable groupID, NSString* _Nullable reqMsg, int32_t joinSource, NSString* _Nullable ex);

FOUNDATION_EXPORT void Im_chat_sdkKickGroupMember(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable groupID, NSString* _Nullable reason, NSString* _Nullable userIDList);

FOUNDATION_EXPORT void Im_chat_sdkLogin(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable userID, NSString* _Nullable token, NSString* _Nullable imToken);

FOUNDATION_EXPORT void Im_chat_sdkLogout(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID);

/**
 * mark as read
 */
FOUNDATION_EXPORT void Im_chat_sdkMarkConversationMessageAsRead(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable conversationID);

FOUNDATION_EXPORT void Im_chat_sdkMarkMessagesAsReadByMsgID(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable conversationID, NSString* _Nullable clientMsgIDs);

FOUNDATION_EXPORT void Im_chat_sdkNetworkStatusChanged(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID);

FOUNDATION_EXPORT Im_chat_sdkLoginMgr* _Nullable Im_chat_sdkNewLoginMgr(void);

FOUNDATION_EXPORT void Im_chat_sdkPinConversation(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable conversationID, BOOL isPinned);

FOUNDATION_EXPORT void Im_chat_sdkPinFriends(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable pinFriendsParams);

FOUNDATION_EXPORT void Im_chat_sdkQuitGroup(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable groupID);

FOUNDATION_EXPORT void Im_chat_sdkRefuseFriendApplication(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable userIDHandleMsg);

FOUNDATION_EXPORT void Im_chat_sdkRefuseGroupApplication(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable groupID, NSString* _Nullable fromUserID, NSString* _Nullable handleMsg);

FOUNDATION_EXPORT void Im_chat_sdkRemoveBlack(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable removeUserID);

FOUNDATION_EXPORT void Im_chat_sdkResetConversationGroupAtType(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable conversationID);

FOUNDATION_EXPORT void Im_chat_sdkRevokeMessage(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable conversationID, NSString* _Nullable clientMsgID);

FOUNDATION_EXPORT void Im_chat_sdkSearchConversation(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable searchParam);

FOUNDATION_EXPORT void Im_chat_sdkSearchFriends(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable searchParam);

FOUNDATION_EXPORT void Im_chat_sdkSearchFullUserInfo(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable keyword, int32_t offset, int32_t limit);

FOUNDATION_EXPORT void Im_chat_sdkSearchGroupMembers(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable searchParam);

FOUNDATION_EXPORT void Im_chat_sdkSearchGroups(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable searchParam);

FOUNDATION_EXPORT void Im_chat_sdkSearchLocalMessages(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable searchParam);

FOUNDATION_EXPORT void Im_chat_sdkSendMessage(id<Im_chat_sdk_callbackSendMsgCallBack> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable message, NSString* _Nullable recvID, NSString* _Nullable groupID, NSString* _Nullable offlinePushInfo, BOOL isOnlineOnly);

FOUNDATION_EXPORT void Im_chat_sdkSendMessageNotOss(id<Im_chat_sdk_callbackSendMsgCallBack> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable message, NSString* _Nullable recvID, NSString* _Nullable groupID, NSString* _Nullable offlinePushInfo, BOOL isOnlineOnly);

FOUNDATION_EXPORT void Im_chat_sdkSetAdvancedMsgListener(id<Im_chat_sdk_callbackOnAdvancedMsgListener> _Nullable listener);

FOUNDATION_EXPORT void Im_chat_sdkSetAppBackgroundStatus(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, BOOL isBackground);

FOUNDATION_EXPORT void Im_chat_sdkSetAppBadge(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, int32_t appUnreadCount);

FOUNDATION_EXPORT void Im_chat_sdkSetBatchMsgListener(id<Im_chat_sdk_callbackOnBatchMsgListener> _Nullable listener);

FOUNDATION_EXPORT void Im_chat_sdkSetContactList(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable contacts);

FOUNDATION_EXPORT void Im_chat_sdkSetContactListener(id<Im_chat_sdk_callbackContactListener> _Nullable listener);

FOUNDATION_EXPORT void Im_chat_sdkSetConversationBurnDuration(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable conversationID, int32_t duration);

FOUNDATION_EXPORT void Im_chat_sdkSetConversationDraft(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable conversationID, NSString* _Nullable draftText);

FOUNDATION_EXPORT void Im_chat_sdkSetConversationEx(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable conversationID, NSString* _Nullable ex);

FOUNDATION_EXPORT void Im_chat_sdkSetConversationIsMsgDestruct(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable conversationID, BOOL isMsgDestruct);

FOUNDATION_EXPORT void Im_chat_sdkSetConversationListener(id<Im_chat_sdk_callbackOnConversationListener> _Nullable listener);

FOUNDATION_EXPORT void Im_chat_sdkSetConversationMsgDestructTime(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable conversationID, int64_t msgDestructTime);

FOUNDATION_EXPORT void Im_chat_sdkSetConversationPrivateChat(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable conversationID, BOOL isPrivate);

FOUNDATION_EXPORT void Im_chat_sdkSetConversationRecvMessageOpt(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable conversationID, long opt);

FOUNDATION_EXPORT void Im_chat_sdkSetCustomBusinessListener(id<Im_chat_sdk_callbackOnCustomBusinessListener> _Nullable listener);

FOUNDATION_EXPORT void Im_chat_sdkSetFriendListener(id<Im_chat_sdk_callbackOnFriendshipListener> _Nullable listener);

FOUNDATION_EXPORT void Im_chat_sdkSetFriendRemark(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable userIDRemark);

FOUNDATION_EXPORT void Im_chat_sdkSetFriendsEx(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable friendIDs, NSString* _Nullable ex);

FOUNDATION_EXPORT void Im_chat_sdkSetGlobalRecvMessageOpt(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, long opt);

FOUNDATION_EXPORT void Im_chat_sdkSetGroupApplyMemberFriend(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable groupID, int32_t rule);

FOUNDATION_EXPORT void Im_chat_sdkSetGroupInfo(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable groupInfo);

FOUNDATION_EXPORT void Im_chat_sdkSetGroupListener(id<Im_chat_sdk_callbackOnGroupListener> _Nullable listener);

FOUNDATION_EXPORT void Im_chat_sdkSetGroupLookMemberInfo(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable groupID, int32_t rule);

FOUNDATION_EXPORT void Im_chat_sdkSetGroupMemberInfo(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable groupMemberInfo);

FOUNDATION_EXPORT void Im_chat_sdkSetGroupMemberNickname(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable groupID, NSString* _Nullable userID, NSString* _Nullable groupMemberNickname);

FOUNDATION_EXPORT void Im_chat_sdkSetGroupMemberRoleLevel(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable groupID, NSString* _Nullable userID, long roleLevel);

FOUNDATION_EXPORT void Im_chat_sdkSetGroupVerification(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable groupID, int32_t verification);

FOUNDATION_EXPORT void Im_chat_sdkSetHeartbeatInterval(long heartbeatInterval);

FOUNDATION_EXPORT void Im_chat_sdkSetMessageKvInfoListener(id<Im_chat_sdk_callbackOnMessageKvInfoListener> _Nullable listener);

FOUNDATION_EXPORT void Im_chat_sdkSetMessageLocalEx(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable conversationID, NSString* _Nullable clientMsgID, NSString* _Nullable localEx);

/**
 * SetSelfInfo sets the user's own information.
Deprecated: user SetSelfInfoEx instead
 */
FOUNDATION_EXPORT void Im_chat_sdkSetSelfInfo(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable userInfo);

/**
 * SetSelfInfoEx sets the user's own information with Ex field.
 */
FOUNDATION_EXPORT void Im_chat_sdkSetSelfInfoEx(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable userInfo);

FOUNDATION_EXPORT void Im_chat_sdkSetUserListener(id<Im_chat_sdk_callbackOnUserListener> _Nullable listener);

FOUNDATION_EXPORT void Im_chat_sdkSetUserNote(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable userNote);

/**
 * SubscribeUsersStatus Presence status of subscribed users.
 */
FOUNDATION_EXPORT void Im_chat_sdkSubscribeUsersStatus(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable userIDs);

FOUNDATION_EXPORT void Im_chat_sdkTransferGroupOwner(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable groupID, NSString* _Nullable newOwnerUserID);

FOUNDATION_EXPORT void Im_chat_sdkTypingStatusUpdate(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable recvID, NSString* _Nullable msgTip);

FOUNDATION_EXPORT void Im_chat_sdkUnInitSDK(NSString* _Nullable operationID);

/**
 * UnsubscribeUsersStatus Unsubscribe a user's presence.
 */
FOUNDATION_EXPORT void Im_chat_sdkUnsubscribeUsersStatus(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable userIDs);

FOUNDATION_EXPORT void Im_chat_sdkUpdateFcmToken(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable fcmToken, int64_t expireTime);

FOUNDATION_EXPORT void Im_chat_sdkUpdateFullUserInfo(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable userInfo);

/**
 * UpdateMsgSenderInfo updates the message sender's nickname and face URL.
 */
FOUNDATION_EXPORT void Im_chat_sdkUpdateMsgSenderInfo(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable nickname, NSString* _Nullable faceURL);

FOUNDATION_EXPORT void Im_chat_sdkUploadFile(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, NSString* _Nullable req, id<Im_chat_sdk_callbackUploadFileCallback> _Nullable progress);

FOUNDATION_EXPORT void Im_chat_sdkUploadLogs(id<Im_chat_sdk_callbackBase> _Nullable callback, NSString* _Nullable operationID, id<Im_chat_sdk_callbackUploadLogProgress> _Nullable progress);

#endif
